<?php

/*
 * SVN Access Manager - a subversion access rights management tool
 * Copyright (C) 2008-2018 Thomas Krieger <tom@svn-access-manager.org>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

/*
 *
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * $Id$
 *
 */
final class FunctionsTest extends PHPUnit_Framework_TestCase {

    private function _execute(array $params = array()) {

        $_GET = $params;
        ob_start();
        include 'functions.php';
        return ob_get_clean();
        
    }

    public function testcheck_string() {

        include_once 'functions.inc.php';
        $this->assertEquals(true, check_string("AGBVFG5654rtref"));
        $this->assertEquals(false, check_string("AGBVFG565\><4rtref"));
        
    }

    public function testcheck_date() {

        include_once 'functions.inc.php';
        
        $this->assertTrue(check_date('12', '12', '2017'));
        $this->assertFalse(check_date('30', '02', '2017'));
        $this->assertFalse(check_date('3a', '03', '2017'));
        $this->assertFalse(check_date('28', 'a3', '2017'));
        $this->assertFalse(check_date('24', '03', '2a17'));
        
    }

    public function testsplitdate() {

        include_once 'functions.inc.php';
        
        $this->assertEquals('11.12.2017', splitdate('20171211'));
        
    }

    public function testGetPhpVersion() {

        $this->assertGreaterThan('50', getPhpVersion());
        
    }

    public function testSplitDateTime() {

        list($date, $time ) = splitDateTime('20160302101112');
        $this->assertEquals('02.03.2016', $date);
        $this->assertEquals('10:11:12', $time);
        
    }

    public function testSplitValiddate() {

        include_once 'functions.inc.php';
        
        $this->assertEquals('11.12.2017', splitValidDate('20171211'));
        
    }

    public function testMkUnixTimestampFromDateTime() {

        $this->assertEquals(1456909872, mkUnixTimestampFromDateTime('20160302101112'));
        
    }

    public function testEncodeHeader() {

        $this->assertEquals('Huijuijui', encode_header('Huijuijui', 'iso-8859-15'));
        
    }

    public function testNoMagicQuotes() {

        $this->assertEquals('SELECT * FROM `eurokurse` WHERE kurs like \%;', no_magic_quotes('SELECT * FROM `eurokurse` WHERE kurs like \%;'));
        
    }

    public function test_getLocale() {

        include_once 'functions.inc.php';
        
        $this->assertEquals('en_US', get_locale());
        
    }

    public function test_initialize_i18n() {

        include_once 'functions.inc.php';
        
        $this->assertNull(initialize_i18n());
        
    }

    public function test_checkLanguage() {

        include_once 'functions.inc.php';
        
        $_SERVER['HTTP_ACCEPT_LANGUAGE'] = 'de_DE';
        $this->assertEquals('de', check_language());
        
        $_SERVER['HTTP_ACCEPT_LANGUAGE'] = 'en_US';
        $this->assertEquals('en', check_language());
        
    }

    public function test_getDateJhjjmmtt() {

        $this->assertEquals(date('Ymd'), getDateJhjjmmtt());
        
    }

    public function test_no_magic_quotes() {

        $this->assertEquals('SELECT * FROM test;', no_magic_quotes('SELECT * FROM test;'));
        
    }

    public function test_digestcrypt() {

        $this->assertEquals('81d477272475b5bcf5fe5659c7b1d05d', digestcrypt('admin', 'huibuh', '1234567890'));
        
    }

    public function test_checkPasswordPolicy() {

        $this->assertEquals(1, checkPasswordPolicy('Start!1234567_', 'y'));
        $this->assertEquals(0, checkPasswordPolicy('123jhy456jfhg7', 'y'));
        $this->assertEquals(0, checkPasswordPolicy('Start!123', 'y'));
        
        $this->assertEquals(1, checkPasswordPolicy('Start!12', 'n'));
        $this->assertEquals(0, checkPasswordPolicy('123jhy45', 'n'));
        $this->assertEquals(0, checkPasswordPolicy('Start!', 'n'));
        
    }

    public function test_check_email() {

        $emailAddresses = array();
        $emailAddresses['q@q.com'] = true;
        $emailAddresses['test.user@test.aaa'] = true;
        $emailAddresses['test.user@test.aarp'] = true;
        $emailAddresses['test.user@test.abarth'] = true;
        $emailAddresses['test.user@test.abb'] = true;
        $emailAddresses['test.user@test.abbott'] = true;
        $emailAddresses['test.user@test.abbvie'] = true;
        $emailAddresses['test.user@test.abc'] = true;
        $emailAddresses['test.user@test.able'] = true;
        $emailAddresses['test.user@test.abogado'] = true;
        $emailAddresses['test.user@test.abudhabi'] = true;
        $emailAddresses['test.user@test.ac'] = true;
        $emailAddresses['test.user@test.academy'] = true;
        $emailAddresses['test.user@test.accenture'] = true;
        $emailAddresses['test.user@test.accountant'] = true;
        $emailAddresses['test.user@test.accountants'] = true;
        $emailAddresses['test.user@test.aco'] = true;
        $emailAddresses['test.user@test.active'] = true;
        $emailAddresses['test.user@test.actor'] = true;
        $emailAddresses['test.user@test.ad'] = true;
        $emailAddresses['test.user@test.adac'] = true;
        $emailAddresses['test.user@test.ads'] = true;
        $emailAddresses['test.user@test.adult'] = true;
        $emailAddresses['test.user@test.ae'] = true;
        $emailAddresses['test.user@test.aeg'] = true;
        $emailAddresses['test.user@test.aero'] = true;
        $emailAddresses['test.user@test.aetna'] = true;
        $emailAddresses['test.user@test.af'] = true;
        $emailAddresses['test.user@test.afamilycompany'] = true;
        $emailAddresses['test.user@test.afl'] = true;
        $emailAddresses['test.user@test.africa'] = true;
        $emailAddresses['test.user@test.ag'] = true;
        $emailAddresses['test.user@test.agakhan'] = true;
        $emailAddresses['test.user@test.agency'] = true;
        $emailAddresses['test.user@test.ai'] = true;
        $emailAddresses['test.user@test.aig'] = true;
        $emailAddresses['test.user@test.aigo'] = true;
        $emailAddresses['test.user@test.airbus'] = true;
        $emailAddresses['test.user@test.airforce'] = true;
        $emailAddresses['test.user@test.airtel'] = true;
        $emailAddresses['test.user@test.akdn'] = true;
        $emailAddresses['test.user@test.al'] = true;
        $emailAddresses['test.user@test.alfaromeo'] = true;
        $emailAddresses['test.user@test.alibaba'] = true;
        $emailAddresses['test.user@test.alipay'] = true;
        $emailAddresses['test.user@test.allfinanz'] = true;
        $emailAddresses['test.user@test.allstate'] = true;
        $emailAddresses['test.user@test.ally'] = true;
        $emailAddresses['test.user@test.alsace'] = true;
        $emailAddresses['test.user@test.alstom'] = true;
        $emailAddresses['test.user@test.am'] = true;
        $emailAddresses['test.user@test.americanexpress'] = true;
        $emailAddresses['test.user@test.americanfamily'] = true;
        $emailAddresses['test.user@test.amex'] = true;
        $emailAddresses['test.user@test.amfam'] = true;
        $emailAddresses['test.user@test.amica'] = true;
        $emailAddresses['test.user@test.amsterdam'] = true;
        $emailAddresses['test.user@test.analytics'] = true;
        $emailAddresses['test.user@test.android'] = true;
        $emailAddresses['test.user@test.anquan'] = true;
        $emailAddresses['test.user@test.anz'] = true;
        $emailAddresses['test.user@test.ao'] = true;
        $emailAddresses['test.user@test.aol'] = true;
        $emailAddresses['test.user@test.apartments'] = true;
        $emailAddresses['test.user@test.app'] = true;
        $emailAddresses['test.user@test.apple'] = true;
        $emailAddresses['test.user@test.aq'] = true;
        $emailAddresses['test.user@test.aquarelle'] = true;
        $emailAddresses['test.user@test.ar'] = true;
        $emailAddresses['test.user@test.arab'] = true;
        $emailAddresses['test.user@test.aramco'] = true;
        $emailAddresses['test.user@test.archi'] = true;
        $emailAddresses['test.user@test.army'] = true;
        $emailAddresses['test.user@test.arpa'] = true;
        $emailAddresses['test.user@test.art'] = true;
        $emailAddresses['test.user@test.arte'] = true;
        $emailAddresses['test.user@test.as'] = true;
        $emailAddresses['test.user@test.asda'] = true;
        $emailAddresses['test.user@test.asia'] = true;
        $emailAddresses['test.user@test.associates'] = true;
        $emailAddresses['test.user@test.at'] = true;
        $emailAddresses['test.user@test.athleta'] = true;
        $emailAddresses['test.user@test.attorney'] = true;
        $emailAddresses['test.user@test.au'] = true;
        $emailAddresses['test.user@test.auction'] = true;
        $emailAddresses['test.user@test.audi'] = true;
        $emailAddresses['test.user@test.audible'] = true;
        $emailAddresses['test.user@test.audio'] = true;
        $emailAddresses['test.user@test.auspost'] = true;
        $emailAddresses['test.user@test.author'] = true;
        $emailAddresses['test.user@test.auto'] = true;
        $emailAddresses['test.user@test.autos'] = true;
        $emailAddresses['test.user@test.avianca'] = true;
        $emailAddresses['test.user@test.aw'] = true;
        $emailAddresses['test.user@test.aws'] = true;
        $emailAddresses['test.user@test.ax'] = true;
        $emailAddresses['test.user@test.axa'] = true;
        $emailAddresses['test.user@test.az'] = true;
        $emailAddresses['test.user@test.azure'] = true;
        $emailAddresses['test.user@test.ba'] = true;
        $emailAddresses['test.user@test.baby'] = true;
        $emailAddresses['test.user@test.baidu'] = true;
        $emailAddresses['test.user@test.banamex'] = true;
        $emailAddresses['test.user@test.bananarepublic'] = true;
        $emailAddresses['test.user@test.band'] = true;
        $emailAddresses['test.user@test.bank'] = true;
        $emailAddresses['test.user@test.bar'] = true;
        $emailAddresses['test.user@test.barcelona'] = true;
        $emailAddresses['test.user@test.barclaycard'] = true;
        $emailAddresses['test.user@test.barclays'] = true;
        $emailAddresses['test.user@test.barefoot'] = true;
        $emailAddresses['test.user@test.bargains'] = true;
        $emailAddresses['test.user@test.baseball'] = true;
        $emailAddresses['test.user@test.basketball'] = true;
        $emailAddresses['test.user@test.bauhaus'] = true;
        $emailAddresses['test.user@test.bayern'] = true;
        $emailAddresses['test.user@test.bb'] = true;
        $emailAddresses['test.user@test.bbc'] = true;
        $emailAddresses['test.user@test.bbt'] = true;
        $emailAddresses['test.user@test.bbva'] = true;
        $emailAddresses['test.user@test.bcg'] = true;
        $emailAddresses['test.user@test.bcn'] = true;
        $emailAddresses['test.user@test.bd'] = true;
        $emailAddresses['test.user@test.be'] = true;
        $emailAddresses['test.user@test.beats'] = true;
        $emailAddresses['test.user@test.beauty'] = true;
        $emailAddresses['test.user@test.beer'] = true;
        $emailAddresses['test.user@test.bentley'] = true;
        $emailAddresses['test.user@test.berlin'] = true;
        $emailAddresses['test.user@test.best'] = true;
        $emailAddresses['test.user@test.bestbuy'] = true;
        $emailAddresses['test.user@test.bet'] = true;
        $emailAddresses['test.user@test.bf'] = true;
        $emailAddresses['test.user@test.bg'] = true;
        $emailAddresses['test.user@test.bh'] = true;
        $emailAddresses['test.user@test.bharti'] = true;
        $emailAddresses['test.user@test.bi'] = true;
        $emailAddresses['test.user@test.bible'] = true;
        $emailAddresses['test.user@test.bid'] = true;
        $emailAddresses['test.user@test.bike'] = true;
        $emailAddresses['test.user@test.bing'] = true;
        $emailAddresses['test.user@test.bingo'] = true;
        $emailAddresses['test.user@test.bio'] = true;
        $emailAddresses['test.user@test.biz'] = true;
        $emailAddresses['test.user@test.bj'] = true;
        $emailAddresses['test.user@test.black'] = true;
        $emailAddresses['test.user@test.blackfriday'] = true;
        $emailAddresses['test.user@test.blanco'] = true;
        $emailAddresses['test.user@test.blockbuster'] = true;
        $emailAddresses['test.user@test.blog'] = true;
        $emailAddresses['test.user@test.bloomberg'] = true;
        $emailAddresses['test.user@test.blue'] = true;
        $emailAddresses['test.user@test.bm'] = true;
        $emailAddresses['test.user@test.bms'] = true;
        $emailAddresses['test.user@test.bmw'] = true;
        $emailAddresses['test.user@test.bn'] = true;
        $emailAddresses['test.user@test.bnl'] = true;
        $emailAddresses['test.user@test.bnpparibas'] = true;
        $emailAddresses['test.user@test.bo'] = true;
        $emailAddresses['test.user@test.boats'] = true;
        $emailAddresses['test.user@test.boehringer'] = true;
        $emailAddresses['test.user@test.bofa'] = true;
        $emailAddresses['test.user@test.bom'] = true;
        $emailAddresses['test.user@test.bond'] = true;
        $emailAddresses['test.user@test.boo'] = true;
        $emailAddresses['test.user@test.book'] = true;
        $emailAddresses['test.user@test.booking'] = true;
        $emailAddresses['test.user@test.boots'] = true;
        $emailAddresses['test.user@test.bosch'] = true;
        $emailAddresses['test.user@test.bostik'] = true;
        $emailAddresses['test.user@test.boston'] = true;
        $emailAddresses['test.user@test.bot'] = true;
        $emailAddresses['test.user@test.boutique'] = true;
        $emailAddresses['test.user@test.box'] = true;
        $emailAddresses['test.user@test.br'] = true;
        $emailAddresses['test.user@test.bradesco'] = true;
        $emailAddresses['test.user@test.bridgestone'] = true;
        $emailAddresses['test.user@test.broadway'] = true;
        $emailAddresses['test.user@test.broker'] = true;
        $emailAddresses['test.user@test.brother'] = true;
        $emailAddresses['test.user@test.brussels'] = true;
        $emailAddresses['test.user@test.bs'] = true;
        $emailAddresses['test.user@test.bt'] = true;
        $emailAddresses['test.user@test.budapest'] = true;
        $emailAddresses['test.user@test.bugatti'] = true;
        $emailAddresses['test.user@test.build'] = true;
        $emailAddresses['test.user@test.builders'] = true;
        $emailAddresses['test.user@test.business'] = true;
        $emailAddresses['test.user@test.buy'] = true;
        $emailAddresses['test.user@test.buzz'] = true;
        $emailAddresses['test.user@test.bv'] = true;
        $emailAddresses['test.user@test.bw'] = true;
        $emailAddresses['test.user@test.by'] = true;
        $emailAddresses['test.user@test.bz'] = true;
        $emailAddresses['test.user@test.bzh'] = true;
        $emailAddresses['test.user@test.ca'] = true;
        $emailAddresses['test.user@test.cab'] = true;
        $emailAddresses['test.user@test.cafe'] = true;
        $emailAddresses['test.user@test.cal'] = true;
        $emailAddresses['test.user@test.call'] = true;
        $emailAddresses['test.user@test.calvinklein'] = true;
        $emailAddresses['test.user@test.cam'] = true;
        $emailAddresses['test.user@test.camera'] = true;
        $emailAddresses['test.user@test.camp'] = true;
        $emailAddresses['test.user@test.cancerresearch'] = true;
        $emailAddresses['test.user@test.canon'] = true;
        $emailAddresses['test.user@test.capetown'] = true;
        $emailAddresses['test.user@test.capital'] = true;
        $emailAddresses['test.user@test.capitalone'] = true;
        $emailAddresses['test.user@test.car'] = true;
        $emailAddresses['test.user@test.caravan'] = true;
        $emailAddresses['test.user@test.cards'] = true;
        $emailAddresses['test.user@test.care'] = true;
        $emailAddresses['test.user@test.career'] = true;
        $emailAddresses['test.user@test.careers'] = true;
        $emailAddresses['test.user@test.cars'] = true;
        $emailAddresses['test.user@test.cartier'] = true;
        $emailAddresses['test.user@test.casa'] = true;
        $emailAddresses['test.user@test.case'] = true;
        $emailAddresses['test.user@test.caseih'] = true;
        $emailAddresses['test.user@test.cash'] = true;
        $emailAddresses['test.user@test.casino'] = true;
        $emailAddresses['test.user@test.cat'] = true;
        $emailAddresses['test.user@test.catering'] = true;
        $emailAddresses['test.user@test.catholic'] = true;
        $emailAddresses['test.user@test.cba'] = true;
        $emailAddresses['test.user@test.cbn'] = true;
        $emailAddresses['test.user@test.cbre'] = true;
        $emailAddresses['test.user@test.cbs'] = true;
        $emailAddresses['test.user@test.cc'] = true;
        $emailAddresses['test.user@test.cd'] = true;
        $emailAddresses['test.user@test.ceb'] = true;
        $emailAddresses['test.user@test.center'] = true;
        $emailAddresses['test.user@test.ceo'] = true;
        $emailAddresses['test.user@test.cern'] = true;
        $emailAddresses['test.user@test.cf'] = true;
        $emailAddresses['test.user@test.cfa'] = true;
        $emailAddresses['test.user@test.cfd'] = true;
        $emailAddresses['test.user@test.cg'] = true;
        $emailAddresses['test.user@test.ch'] = true;
        $emailAddresses['test.user@test.chanel'] = true;
        $emailAddresses['test.user@test.channel'] = true;
        $emailAddresses['test.user@test.chase'] = true;
        $emailAddresses['test.user@test.chat'] = true;
        $emailAddresses['test.user@test.cheap'] = true;
        $emailAddresses['test.user@test.chintai'] = true;
        $emailAddresses['test.user@test.christmas'] = true;
        $emailAddresses['test.user@test.chrome'] = true;
        $emailAddresses['test.user@test.chrysler'] = true;
        $emailAddresses['test.user@test.church'] = true;
        $emailAddresses['test.user@test.ci'] = true;
        $emailAddresses['test.user@test.cipriani'] = true;
        $emailAddresses['test.user@test.circle'] = true;
        $emailAddresses['test.user@test.cisco'] = true;
        $emailAddresses['test.user@test.citadel'] = true;
        $emailAddresses['test.user@test.citi'] = true;
        $emailAddresses['test.user@test.citic'] = true;
        $emailAddresses['test.user@test.city'] = true;
        $emailAddresses['test.user@test.cityeats'] = true;
        $emailAddresses['test.user@test.ck'] = true;
        $emailAddresses['test.user@test.cl'] = true;
        $emailAddresses['test.user@test.claims'] = true;
        $emailAddresses['test.user@test.cleaning'] = true;
        $emailAddresses['test.user@test.click'] = true;
        $emailAddresses['test.user@test.clinic'] = true;
        $emailAddresses['test.user@test.clinique'] = true;
        $emailAddresses['test.user@test.clothing'] = true;
        $emailAddresses['test.user@test.cloud'] = true;
        $emailAddresses['test.user@test.club'] = true;
        $emailAddresses['test.user@test.clubmed'] = true;
        $emailAddresses['test.user@test.cm'] = true;
        $emailAddresses['test.user@test.cn'] = true;
        $emailAddresses['test.user@test.co'] = true;
        $emailAddresses['test.user@test.coach'] = true;
        $emailAddresses['test.user@test.codes'] = true;
        $emailAddresses['test.user@test.coffee'] = true;
        $emailAddresses['test.user@test.college'] = true;
        $emailAddresses['test.user@test.cologne'] = true;
        $emailAddresses['test.user@test.com'] = true;
        $emailAddresses['test.user@test.comcast'] = true;
        $emailAddresses['test.user@test.commbank'] = true;
        $emailAddresses['test.user@test.community'] = true;
        $emailAddresses['test.user@test.company'] = true;
        $emailAddresses['test.user@test.compare'] = true;
        $emailAddresses['test.user@test.computer'] = true;
        $emailAddresses['test.user@test.comsec'] = true;
        $emailAddresses['test.user@test.condos'] = true;
        $emailAddresses['test.user@test.construction'] = true;
        $emailAddresses['test.user@test.consulting'] = true;
        $emailAddresses['test.user@test.contact'] = true;
        $emailAddresses['test.user@test.contractors'] = true;
        $emailAddresses['test.user@test.cooking'] = true;
        $emailAddresses['test.user@test.cookingchannel'] = true;
        $emailAddresses['test.user@test.cool'] = true;
        $emailAddresses['test.user@test.coop'] = true;
        $emailAddresses['test.user@test.corsica'] = true;
        $emailAddresses['test.user@test.country'] = true;
        $emailAddresses['test.user@test.coupon'] = true;
        $emailAddresses['test.user@test.coupons'] = true;
        $emailAddresses['test.user@test.courses'] = true;
        $emailAddresses['test.user@test.cr'] = true;
        $emailAddresses['test.user@test.credit'] = true;
        $emailAddresses['test.user@test.creditcard'] = true;
        $emailAddresses['test.user@test.creditunion'] = true;
        $emailAddresses['test.user@test.cricket'] = true;
        $emailAddresses['test.user@test.crown'] = true;
        $emailAddresses['test.user@test.crs'] = true;
        $emailAddresses['test.user@test.cruise'] = true;
        $emailAddresses['test.user@test.cruises'] = true;
        $emailAddresses['test.user@test.csc'] = true;
        $emailAddresses['test.user@test.cu'] = true;
        $emailAddresses['test.user@test.cuisinella'] = true;
        $emailAddresses['test.user@test.cv'] = true;
        $emailAddresses['test.user@test.cw'] = true;
        $emailAddresses['test.user@test.cx'] = true;
        $emailAddresses['test.user@test.cy'] = true;
        $emailAddresses['test.user@test.cymru'] = true;
        $emailAddresses['test.user@test.cyou'] = true;
        $emailAddresses['test.user@test.cz'] = true;
        $emailAddresses['test.user@test.dabur'] = true;
        $emailAddresses['test.user@test.dad'] = true;
        $emailAddresses['test.user@test.dance'] = true;
        $emailAddresses['test.user@test.data'] = true;
        $emailAddresses['test.user@test.date'] = true;
        $emailAddresses['test.user@test.dating'] = true;
        $emailAddresses['test.user@test.datsun'] = true;
        $emailAddresses['test.user@test.day'] = true;
        $emailAddresses['test.user@test.dclk'] = true;
        $emailAddresses['test.user@test.dds'] = true;
        $emailAddresses['test.user@test.de'] = true;
        $emailAddresses['test.user@test.deal'] = true;
        $emailAddresses['test.user@test.dealer'] = true;
        $emailAddresses['test.user@test.deals'] = true;
        $emailAddresses['test.user@test.degree'] = true;
        $emailAddresses['test.user@test.delivery'] = true;
        $emailAddresses['test.user@test.dell'] = true;
        $emailAddresses['test.user@test.deloitte'] = true;
        $emailAddresses['test.user@test.delta'] = true;
        $emailAddresses['test.user@test.democrat'] = true;
        $emailAddresses['test.user@test.dental'] = true;
        $emailAddresses['test.user@test.dentist'] = true;
        $emailAddresses['test.user@test.desi'] = true;
        $emailAddresses['test.user@test.design'] = true;
        $emailAddresses['test.user@test.dev'] = true;
        $emailAddresses['test.user@test.dhl'] = true;
        $emailAddresses['test.user@test.diamonds'] = true;
        $emailAddresses['test.user@test.diet'] = true;
        $emailAddresses['test.user@test.digital'] = true;
        $emailAddresses['test.user@test.direct'] = true;
        $emailAddresses['test.user@test.directory'] = true;
        $emailAddresses['test.user@test.discount'] = true;
        $emailAddresses['test.user@test.discover'] = true;
        $emailAddresses['test.user@test.dish'] = true;
        $emailAddresses['test.user@test.diy'] = true;
        $emailAddresses['test.user@test.dj'] = true;
        $emailAddresses['test.user@test.dk'] = true;
        $emailAddresses['test.user@test.dm'] = true;
        $emailAddresses['test.user@test.dnp'] = true;
        $emailAddresses['test.user@test.do'] = true;
        $emailAddresses['test.user@test.docs'] = true;
        $emailAddresses['test.user@test.doctor'] = true;
        $emailAddresses['test.user@test.dodge'] = true;
        $emailAddresses['test.user@test.dog'] = true;
        $emailAddresses['test.user@test.doha'] = true;
        $emailAddresses['test.user@test.domains'] = true;
        $emailAddresses['test.user@test.dot'] = true;
        $emailAddresses['test.user@test.download'] = true;
        $emailAddresses['test.user@test.drive'] = true;
        $emailAddresses['test.user@test.dtv'] = true;
        $emailAddresses['test.user@test.dubai'] = true;
        $emailAddresses['test.user@test.duck'] = true;
        $emailAddresses['test.user@test.dunlop'] = true;
        $emailAddresses['test.user@test.duns'] = true;
        $emailAddresses['test.user@test.dupont'] = true;
        $emailAddresses['test.user@test.durban'] = true;
        $emailAddresses['test.user@test.dvag'] = true;
        $emailAddresses['test.user@test.dvr'] = true;
        $emailAddresses['test.user@test.dz'] = true;
        $emailAddresses['test.user@test.earth'] = true;
        $emailAddresses['test.user@test.eat'] = true;
        $emailAddresses['test.user@test.ec'] = true;
        $emailAddresses['test.user@test.eco'] = true;
        $emailAddresses['test.user@test.edeka'] = true;
        $emailAddresses['test.user@test.edu'] = true;
        $emailAddresses['test.user@test.education'] = true;
        $emailAddresses['test.user@test.ee'] = true;
        $emailAddresses['test.user@test.eg'] = true;
        $emailAddresses['test.user@test.email'] = true;
        $emailAddresses['test.user@test.emerck'] = true;
        $emailAddresses['test.user@test.energy'] = true;
        $emailAddresses['test.user@test.engineer'] = true;
        $emailAddresses['test.user@test.engineering'] = true;
        $emailAddresses['test.user@test.enterprises'] = true;
        $emailAddresses['test.user@test.epost'] = true;
        $emailAddresses['test.user@test.epson'] = true;
        $emailAddresses['test.user@test.equipment'] = true;
        $emailAddresses['test.user@test.er'] = true;
        $emailAddresses['test.user@test.ericsson'] = true;
        $emailAddresses['test.user@test.erni'] = true;
        $emailAddresses['test.user@test.es'] = true;
        $emailAddresses['test.user@test.esq'] = true;
        $emailAddresses['test.user@test.estate'] = true;
        $emailAddresses['test.user@test.esurance'] = true;
        $emailAddresses['test.user@test.et'] = true;
        $emailAddresses['test.user@test.etisalat'] = true;
        $emailAddresses['test.user@test.eu'] = true;
        $emailAddresses['test.user@test.eurovision'] = true;
        $emailAddresses['test.user@test.eus'] = true;
        $emailAddresses['test.user@test.events'] = true;
        $emailAddresses['test.user@test.everbank'] = true;
        $emailAddresses['test.user@test.exchange'] = true;
        $emailAddresses['test.user@test.expert'] = true;
        $emailAddresses['test.user@test.exposed'] = true;
        $emailAddresses['test.user@test.express'] = true;
        $emailAddresses['test.user@test.extraspace'] = true;
        $emailAddresses['test.user@test.fage'] = true;
        $emailAddresses['test.user@test.fail'] = true;
        $emailAddresses['test.user@test.fairwinds'] = true;
        $emailAddresses['test.user@test.faith'] = true;
        $emailAddresses['test.user@test.family'] = true;
        $emailAddresses['test.user@test.fan'] = true;
        $emailAddresses['test.user@test.fans'] = true;
        $emailAddresses['test.user@test.farm'] = true;
        $emailAddresses['test.user@test.farmers'] = true;
        $emailAddresses['test.user@test.fashion'] = true;
        $emailAddresses['test.user@test.fast'] = true;
        $emailAddresses['test.user@test.fedex'] = true;
        $emailAddresses['test.user@test.feedback'] = true;
        $emailAddresses['test.user@test.ferrari'] = true;
        $emailAddresses['test.user@test.ferrero'] = true;
        $emailAddresses['test.user@test.fi'] = true;
        $emailAddresses['test.user@test.fiat'] = true;
        $emailAddresses['test.user@test.fidelity'] = true;
        $emailAddresses['test.user@test.fido'] = true;
        $emailAddresses['test.user@test.film'] = true;
        $emailAddresses['test.user@test.final'] = true;
        $emailAddresses['test.user@test.finance'] = true;
        $emailAddresses['test.user@test.financial'] = true;
        $emailAddresses['test.user@test.fire'] = true;
        $emailAddresses['test.user@test.firestone'] = true;
        $emailAddresses['test.user@test.firmdale'] = true;
        $emailAddresses['test.user@test.fish'] = true;
        $emailAddresses['test.user@test.fishing'] = true;
        $emailAddresses['test.user@test.fit'] = true;
        $emailAddresses['test.user@test.fitness'] = true;
        $emailAddresses['test.user@test.fj'] = true;
        $emailAddresses['test.user@test.fk'] = true;
        $emailAddresses['test.user@test.flickr'] = true;
        $emailAddresses['test.user@test.flights'] = true;
        $emailAddresses['test.user@test.flir'] = true;
        $emailAddresses['test.user@test.florist'] = true;
        $emailAddresses['test.user@test.flowers'] = true;
        $emailAddresses['test.user@test.fly'] = true;
        $emailAddresses['test.user@test.fm'] = true;
        $emailAddresses['test.user@test.fo'] = true;
        $emailAddresses['test.user@test.foo'] = true;
        $emailAddresses['test.user@test.food'] = true;
        $emailAddresses['test.user@test.foodnetwork'] = true;
        $emailAddresses['test.user@test.football'] = true;
        $emailAddresses['test.user@test.ford'] = true;
        $emailAddresses['test.user@test.forex'] = true;
        $emailAddresses['test.user@test.forsale'] = true;
        $emailAddresses['test.user@test.forum'] = true;
        $emailAddresses['test.user@test.foundation'] = true;
        $emailAddresses['test.user@test.fox'] = true;
        $emailAddresses['test.user@test.fr'] = true;
        $emailAddresses['test.user@test.free'] = true;
        $emailAddresses['test.user@test.fresenius'] = true;
        $emailAddresses['test.user@test.frl'] = true;
        $emailAddresses['test.user@test.frogans'] = true;
        $emailAddresses['test.user@test.frontdoor'] = true;
        $emailAddresses['test.user@test.frontier'] = true;
        $emailAddresses['test.user@test.ftr'] = true;
        $emailAddresses['test.user@test.fujitsu'] = true;
        $emailAddresses['test.user@test.fujixerox'] = true;
        $emailAddresses['test.user@test.fun'] = true;
        $emailAddresses['test.user@test.fund'] = true;
        $emailAddresses['test.user@test.furniture'] = true;
        $emailAddresses['test.user@test.futbol'] = true;
        $emailAddresses['test.user@test.fyi'] = true;
        $emailAddresses['test.user@test.ga'] = true;
        $emailAddresses['test.user@test.gal'] = true;
        $emailAddresses['test.user@test.gallery'] = true;
        $emailAddresses['test.user@test.gallo'] = true;
        $emailAddresses['test.user@test.gallup'] = true;
        $emailAddresses['test.user@test.game'] = true;
        $emailAddresses['test.user@test.games'] = true;
        $emailAddresses['test.user@test.gap'] = true;
        $emailAddresses['test.user@test.garden'] = true;
        $emailAddresses['test.user@test.gb'] = true;
        $emailAddresses['test.user@test.gbiz'] = true;
        $emailAddresses['test.user@test.gd'] = true;
        $emailAddresses['test.user@test.gdn'] = true;
        $emailAddresses['test.user@test.ge'] = true;
        $emailAddresses['test.user@test.gea'] = true;
        $emailAddresses['test.user@test.gent'] = true;
        $emailAddresses['test.user@test.genting'] = true;
        $emailAddresses['test.user@test.george'] = true;
        $emailAddresses['test.user@test.gf'] = true;
        $emailAddresses['test.user@test.gg'] = true;
        $emailAddresses['test.user@test.ggee'] = true;
        $emailAddresses['test.user@test.gh'] = true;
        $emailAddresses['test.user@test.gi'] = true;
        $emailAddresses['test.user@test.gift'] = true;
        $emailAddresses['test.user@test.gifts'] = true;
        $emailAddresses['test.user@test.gives'] = true;
        $emailAddresses['test.user@test.giving'] = true;
        $emailAddresses['test.user@test.gl'] = true;
        $emailAddresses['test.user@test.glade'] = true;
        $emailAddresses['test.user@test.glass'] = true;
        $emailAddresses['test.user@test.gle'] = true;
        $emailAddresses['test.user@test.global'] = true;
        $emailAddresses['test.user@test.globo'] = true;
        $emailAddresses['test.user@test.gm'] = true;
        $emailAddresses['test.user@test.gmail'] = true;
        $emailAddresses['test.user@test.gmbh'] = true;
        $emailAddresses['test.user@test.gmo'] = true;
        $emailAddresses['test.user@test.gmx'] = true;
        $emailAddresses['test.user@test.gn'] = true;
        $emailAddresses['test.user@test.godaddy'] = true;
        $emailAddresses['test.user@test.gold'] = true;
        $emailAddresses['test.user@test.goldpoint'] = true;
        $emailAddresses['test.user@test.golf'] = true;
        $emailAddresses['test.user@test.goo'] = true;
        $emailAddresses['test.user@test.goodhands'] = true;
        $emailAddresses['test.user@test.goodyear'] = true;
        $emailAddresses['test.user@test.goog'] = true;
        $emailAddresses['test.user@test.google'] = true;
        $emailAddresses['test.user@test.gop'] = true;
        $emailAddresses['test.user@test.got'] = true;
        $emailAddresses['test.user@test.gov'] = true;
        $emailAddresses['test.user@test.gp'] = true;
        $emailAddresses['test.user@test.gq'] = true;
        $emailAddresses['test.user@test.gr'] = true;
        $emailAddresses['test.user@test.grainger'] = true;
        $emailAddresses['test.user@test.graphics'] = true;
        $emailAddresses['test.user@test.gratis'] = true;
        $emailAddresses['test.user@test.green'] = true;
        $emailAddresses['test.user@test.gripe'] = true;
        $emailAddresses['test.user@test.grocery'] = true;
        $emailAddresses['test.user@test.group'] = true;
        $emailAddresses['test.user@test.gs'] = true;
        $emailAddresses['test.user@test.gt'] = true;
        $emailAddresses['test.user@test.gu'] = true;
        $emailAddresses['test.user@test.guardian'] = true;
        $emailAddresses['test.user@test.gucci'] = true;
        $emailAddresses['test.user@test.guge'] = true;
        $emailAddresses['test.user@test.guide'] = true;
        $emailAddresses['test.user@test.guitars'] = true;
        $emailAddresses['test.user@test.guru'] = true;
        $emailAddresses['test.user@test.gw'] = true;
        $emailAddresses['test.user@test.gy'] = true;
        $emailAddresses['test.user@test.hair'] = true;
        $emailAddresses['test.user@test.hamburg'] = true;
        $emailAddresses['test.user@test.hangout'] = true;
        $emailAddresses['test.user@test.haus'] = true;
        $emailAddresses['test.user@test.hbo'] = true;
        $emailAddresses['test.user@test.hdfc'] = true;
        $emailAddresses['test.user@test.hdfcbank'] = true;
        $emailAddresses['test.user@test.health'] = true;
        $emailAddresses['test.user@test.healthcare'] = true;
        $emailAddresses['test.user@test.help'] = true;
        $emailAddresses['test.user@test.helsinki'] = true;
        $emailAddresses['test.user@test.here'] = true;
        $emailAddresses['test.user@test.hermes'] = true;
        $emailAddresses['test.user@test.hgtv'] = true;
        $emailAddresses['test.user@test.hiphop'] = true;
        $emailAddresses['test.user@test.hisamitsu'] = true;
        $emailAddresses['test.user@test.hitachi'] = true;
        $emailAddresses['test.user@test.hiv'] = true;
        $emailAddresses['test.user@test.hk'] = true;
        $emailAddresses['test.user@test.hkt'] = true;
        $emailAddresses['test.user@test.hm'] = true;
        $emailAddresses['test.user@test.hn'] = true;
        $emailAddresses['test.user@test.hockey'] = true;
        $emailAddresses['test.user@test.holdings'] = true;
        $emailAddresses['test.user@test.holiday'] = true;
        $emailAddresses['test.user@test.homedepot'] = true;
        $emailAddresses['test.user@test.homegoods'] = true;
        $emailAddresses['test.user@test.homes'] = true;
        $emailAddresses['test.user@test.homesense'] = true;
        $emailAddresses['test.user@test.honda'] = true;
        $emailAddresses['test.user@test.honeywell'] = true;
        $emailAddresses['test.user@test.horse'] = true;
        $emailAddresses['test.user@test.hospital'] = true;
        $emailAddresses['test.user@test.host'] = true;
        $emailAddresses['test.user@test.hosting'] = true;
        $emailAddresses['test.user@test.hot'] = true;
        $emailAddresses['test.user@test.hoteles'] = true;
        $emailAddresses['test.user@test.hotels'] = true;
        $emailAddresses['test.user@test.hotmail'] = true;
        $emailAddresses['test.user@test.house'] = true;
        $emailAddresses['test.user@test.how'] = true;
        $emailAddresses['test.user@test.hr'] = true;
        $emailAddresses['test.user@test.hsbc'] = true;
        $emailAddresses['test.user@test.ht'] = true;
        $emailAddresses['test.user@test.hu'] = true;
        $emailAddresses['test.user@test.hughes'] = true;
        $emailAddresses['test.user@test.hyatt'] = true;
        $emailAddresses['test.user@test.hyundai'] = true;
        $emailAddresses['test.user@test.ibm'] = true;
        $emailAddresses['test.user@test.icbc'] = true;
        $emailAddresses['test.user@test.ice'] = true;
        $emailAddresses['test.user@test.icu'] = true;
        $emailAddresses['test.user@test.id'] = true;
        $emailAddresses['test.user@test.ie'] = true;
        $emailAddresses['test.user@test.ieee'] = true;
        $emailAddresses['test.user@test.ifm'] = true;
        $emailAddresses['test.user@test.ikano'] = true;
        $emailAddresses['test.user@test.il'] = true;
        $emailAddresses['test.user@test.im'] = true;
        $emailAddresses['test.user@test.imamat'] = true;
        $emailAddresses['test.user@test.imdb'] = true;
        $emailAddresses['test.user@test.immo'] = true;
        $emailAddresses['test.user@test.immobilien'] = true;
        $emailAddresses['test.user@test.in'] = true;
        $emailAddresses['test.user@test.industries'] = true;
        $emailAddresses['test.user@test.infiniti'] = true;
        $emailAddresses['test.user@test.info'] = true;
        $emailAddresses['test.user@test.ing'] = true;
        $emailAddresses['test.user@test.ink'] = true;
        $emailAddresses['test.user@test.institute'] = true;
        $emailAddresses['test.user@test.insurance'] = true;
        $emailAddresses['test.user@test.insure'] = true;
        $emailAddresses['test.user@test.int'] = true;
        $emailAddresses['test.user@test.intel'] = true;
        $emailAddresses['test.user@test.international'] = true;
        $emailAddresses['test.user@test.intuit'] = true;
        $emailAddresses['test.user@test.investments'] = true;
        $emailAddresses['test.user@test.io'] = true;
        $emailAddresses['test.user@test.ipiranga'] = true;
        $emailAddresses['test.user@test.iq'] = true;
        $emailAddresses['test.user@test.ir'] = true;
        $emailAddresses['test.user@test.irish'] = true;
        $emailAddresses['test.user@test.is'] = true;
        $emailAddresses['test.user@test.iselect'] = true;
        $emailAddresses['test.user@test.ismaili'] = true;
        $emailAddresses['test.user@test.ist'] = true;
        $emailAddresses['test.user@test.istanbul'] = true;
        $emailAddresses['test.user@test.it'] = true;
        $emailAddresses['test.user@test.itau'] = true;
        $emailAddresses['test.user@test.itv'] = true;
        $emailAddresses['test.user@test.iveco'] = true;
        $emailAddresses['test.user@test.iwc'] = true;
        $emailAddresses['test.user@test.jaguar'] = true;
        $emailAddresses['test.user@test.java'] = true;
        $emailAddresses['test.user@test.jcb'] = true;
        $emailAddresses['test.user@test.jcp'] = true;
        $emailAddresses['test.user@test.je'] = true;
        $emailAddresses['test.user@test.jeep'] = true;
        $emailAddresses['test.user@test.jetzt'] = true;
        $emailAddresses['test.user@test.jewelry'] = true;
        $emailAddresses['test.user@test.jio'] = true;
        $emailAddresses['test.user@test.jlc'] = true;
        $emailAddresses['test.user@test.jll'] = true;
        $emailAddresses['test.user@test.jm'] = true;
        $emailAddresses['test.user@test.jmp'] = true;
        $emailAddresses['test.user@test.jnj'] = true;
        $emailAddresses['test.user@test.jo'] = true;
        $emailAddresses['test.user@test.jobs'] = true;
        $emailAddresses['test.user@test.joburg'] = true;
        $emailAddresses['test.user@test.jot'] = true;
        $emailAddresses['test.user@test.joy'] = true;
        $emailAddresses['test.user@test.jp'] = true;
        $emailAddresses['test.user@test.jpmorgan'] = true;
        $emailAddresses['test.user@test.jprs'] = true;
        $emailAddresses['test.user@test.juegos'] = true;
        $emailAddresses['test.user@test.juniper'] = true;
        $emailAddresses['test.user@test.kaufen'] = true;
        $emailAddresses['test.user@test.kddi'] = true;
        $emailAddresses['test.user@test.ke'] = true;
        $emailAddresses['test.user@test.kerryhotels'] = true;
        $emailAddresses['test.user@test.kerrylogistics'] = true;
        $emailAddresses['test.user@test.kerryproperties'] = true;
        $emailAddresses['test.user@test.kfh'] = true;
        $emailAddresses['test.user@test.kg'] = true;
        $emailAddresses['test.user@test.kh'] = true;
        $emailAddresses['test.user@test.ki'] = true;
        $emailAddresses['test.user@test.kia'] = true;
        $emailAddresses['test.user@test.kim'] = true;
        $emailAddresses['test.user@test.kinder'] = true;
        $emailAddresses['test.user@test.kindle'] = true;
        $emailAddresses['test.user@test.kitchen'] = true;
        $emailAddresses['test.user@test.kiwi'] = true;
        $emailAddresses['test.user@test.km'] = true;
        $emailAddresses['test.user@test.kn'] = true;
        $emailAddresses['test.user@test.koeln'] = true;
        $emailAddresses['test.user@test.komatsu'] = true;
        $emailAddresses['test.user@test.kosher'] = true;
        $emailAddresses['test.user@test.kp'] = true;
        $emailAddresses['test.user@test.kpmg'] = true;
        $emailAddresses['test.user@test.kpn'] = true;
        $emailAddresses['test.user@test.kr'] = true;
        $emailAddresses['test.user@test.krd'] = true;
        $emailAddresses['test.user@test.kred'] = true;
        $emailAddresses['test.user@test.kuokgroup'] = true;
        $emailAddresses['test.user@test.kw'] = true;
        $emailAddresses['test.user@test.ky'] = true;
        $emailAddresses['test.user@test.kyoto'] = true;
        $emailAddresses['test.user@test.kz'] = true;
        $emailAddresses['test.user@test.la'] = true;
        $emailAddresses['test.user@test.lacaixa'] = true;
        $emailAddresses['test.user@test.ladbrokes'] = true;
        $emailAddresses['test.user@test.lamborghini'] = true;
        $emailAddresses['test.user@test.lamer'] = true;
        $emailAddresses['test.user@test.lancaster'] = true;
        $emailAddresses['test.user@test.lancia'] = true;
        $emailAddresses['test.user@test.lancome'] = true;
        $emailAddresses['test.user@test.land'] = true;
        $emailAddresses['test.user@test.landrover'] = true;
        $emailAddresses['test.user@test.lanxess'] = true;
        $emailAddresses['test.user@test.lasalle'] = true;
        $emailAddresses['test.user@test.lat'] = true;
        $emailAddresses['test.user@test.latino'] = true;
        $emailAddresses['test.user@test.latrobe'] = true;
        $emailAddresses['test.user@test.law'] = true;
        $emailAddresses['test.user@test.lawyer'] = true;
        $emailAddresses['test.user@test.lb'] = true;
        $emailAddresses['test.user@test.lc'] = true;
        $emailAddresses['test.user@test.lds'] = true;
        $emailAddresses['test.user@test.lease'] = true;
        $emailAddresses['test.user@test.leclerc'] = true;
        $emailAddresses['test.user@test.lefrak'] = true;
        $emailAddresses['test.user@test.legal'] = true;
        $emailAddresses['test.user@test.lego'] = true;
        $emailAddresses['test.user@test.lexus'] = true;
        $emailAddresses['test.user@test.lgbt'] = true;
        $emailAddresses['test.user@test.li'] = true;
        $emailAddresses['test.user@test.liaison'] = true;
        $emailAddresses['test.user@test.lidl'] = true;
        $emailAddresses['test.user@test.life'] = true;
        $emailAddresses['test.user@test.lifeinsurance'] = true;
        $emailAddresses['test.user@test.lifestyle'] = true;
        $emailAddresses['test.user@test.lighting'] = true;
        $emailAddresses['test.user@test.like'] = true;
        $emailAddresses['test.user@test.lilly'] = true;
        $emailAddresses['test.user@test.limited'] = true;
        $emailAddresses['test.user@test.limo'] = true;
        $emailAddresses['test.user@test.lincoln'] = true;
        $emailAddresses['test.user@test.linde'] = true;
        $emailAddresses['test.user@test.link'] = true;
        $emailAddresses['test.user@test.lipsy'] = true;
        $emailAddresses['test.user@test.live'] = true;
        $emailAddresses['test.user@test.living'] = true;
        $emailAddresses['test.user@test.lixil'] = true;
        $emailAddresses['test.user@test.lk'] = true;
        $emailAddresses['test.user@test.llc'] = true;
        $emailAddresses['test.user@test.loan'] = true;
        $emailAddresses['test.user@test.loans'] = true;
        $emailAddresses['test.user@test.locker'] = true;
        $emailAddresses['test.user@test.locus'] = true;
        $emailAddresses['test.user@test.loft'] = true;
        $emailAddresses['test.user@test.lol'] = true;
        $emailAddresses['test.user@test.london'] = true;
        $emailAddresses['test.user@test.lotte'] = true;
        $emailAddresses['test.user@test.lotto'] = true;
        $emailAddresses['test.user@test.love'] = true;
        $emailAddresses['test.user@test.lpl'] = true;
        $emailAddresses['test.user@test.lplfinancial'] = true;
        $emailAddresses['test.user@test.lr'] = true;
        $emailAddresses['test.user@test.ls'] = true;
        $emailAddresses['test.user@test.lt'] = true;
        $emailAddresses['test.user@test.ltd'] = true;
        $emailAddresses['test.user@test.ltda'] = true;
        $emailAddresses['test.user@test.lu'] = true;
        $emailAddresses['test.user@test.lundbeck'] = true;
        $emailAddresses['test.user@test.lupin'] = true;
        $emailAddresses['test.user@test.luxe'] = true;
        $emailAddresses['test.user@test.luxury'] = true;
        $emailAddresses['test.user@test.lv'] = true;
        $emailAddresses['test.user@test.ly'] = true;
        $emailAddresses['test.user@test.ma'] = true;
        $emailAddresses['test.user@test.macys'] = true;
        $emailAddresses['test.user@test.madrid'] = true;
        $emailAddresses['test.user@test.maif'] = true;
        $emailAddresses['test.user@test.maison'] = true;
        $emailAddresses['test.user@test.makeup'] = true;
        $emailAddresses['test.user@test.man'] = true;
        $emailAddresses['test.user@test.management'] = true;
        $emailAddresses['test.user@test.mango'] = true;
        $emailAddresses['test.user@test.map'] = true;
        $emailAddresses['test.user@test.market'] = true;
        $emailAddresses['test.user@test.marketing'] = true;
        $emailAddresses['test.user@test.markets'] = true;
        $emailAddresses['test.user@test.marriott'] = true;
        $emailAddresses['test.user@test.marshalls'] = true;
        $emailAddresses['test.user@test.maserati'] = true;
        $emailAddresses['test.user@test.mattel'] = true;
        $emailAddresses['test.user@test.mba'] = true;
        $emailAddresses['test.user@test.mc'] = true;
        $emailAddresses['test.user@test.mckinsey'] = true;
        $emailAddresses['test.user@test.md'] = true;
        $emailAddresses['test.user@test.me'] = true;
        $emailAddresses['test.user@test.med'] = true;
        $emailAddresses['test.user@test.media'] = true;
        $emailAddresses['test.user@test.meet'] = true;
        $emailAddresses['test.user@test.melbourne'] = true;
        $emailAddresses['test.user@test.meme'] = true;
        $emailAddresses['test.user@test.memorial'] = true;
        $emailAddresses['test.user@test.men'] = true;
        $emailAddresses['test.user@test.menu'] = true;
        $emailAddresses['test.user@test.meo'] = true;
        $emailAddresses['test.user@test.merckmsd'] = true;
        $emailAddresses['test.user@test.metlife'] = true;
        $emailAddresses['test.user@test.mg'] = true;
        $emailAddresses['test.user@test.mh'] = true;
        $emailAddresses['test.user@test.miami'] = true;
        $emailAddresses['test.user@test.microsoft'] = true;
        $emailAddresses['test.user@test.mil'] = true;
        $emailAddresses['test.user@test.mini'] = true;
        $emailAddresses['test.user@test.mint'] = true;
        $emailAddresses['test.user@test.mit'] = true;
        $emailAddresses['test.user@test.mitsubishi'] = true;
        $emailAddresses['test.user@test.mk'] = true;
        $emailAddresses['test.user@test.ml'] = true;
        $emailAddresses['test.user@test.mlb'] = true;
        $emailAddresses['test.user@test.mls'] = true;
        $emailAddresses['test.user@test.mm'] = true;
        $emailAddresses['test.user@test.mma'] = true;
        $emailAddresses['test.user@test.mn'] = true;
        $emailAddresses['test.user@test.mo'] = true;
        $emailAddresses['test.user@test.mobi'] = true;
        $emailAddresses['test.user@test.mobile'] = true;
        $emailAddresses['test.user@test.mobily'] = true;
        $emailAddresses['test.user@test.moda'] = true;
        $emailAddresses['test.user@test.moe'] = true;
        $emailAddresses['test.user@test.moi'] = true;
        $emailAddresses['test.user@test.mom'] = true;
        $emailAddresses['test.user@test.monash'] = true;
        $emailAddresses['test.user@test.money'] = true;
        $emailAddresses['test.user@test.monster'] = true;
        $emailAddresses['test.user@test.mopar'] = true;
        $emailAddresses['test.user@test.mormon'] = true;
        $emailAddresses['test.user@test.mortgage'] = true;
        $emailAddresses['test.user@test.moscow'] = true;
        $emailAddresses['test.user@test.moto'] = true;
        $emailAddresses['test.user@test.motorcycles'] = true;
        $emailAddresses['test.user@test.mov'] = true;
        $emailAddresses['test.user@test.movie'] = true;
        $emailAddresses['test.user@test.movistar'] = true;
        $emailAddresses['test.user@test.mp'] = true;
        $emailAddresses['test.user@test.mq'] = true;
        $emailAddresses['test.user@test.mr'] = true;
        $emailAddresses['test.user@test.ms'] = true;
        $emailAddresses['test.user@test.msd'] = true;
        $emailAddresses['test.user@test.mt'] = true;
        $emailAddresses['test.user@test.mtn'] = true;
        $emailAddresses['test.user@test.mtr'] = true;
        $emailAddresses['test.user@test.mu'] = true;
        $emailAddresses['test.user@test.museum'] = true;
        $emailAddresses['test.user@test.mutual'] = true;
        $emailAddresses['test.user@test.mv'] = true;
        $emailAddresses['test.user@test.mw'] = true;
        $emailAddresses['test.user@test.mx'] = true;
        $emailAddresses['test.user@test.my'] = true;
        $emailAddresses['test.user@test.mz'] = true;
        $emailAddresses['test.user@test.na'] = true;
        $emailAddresses['test.user@test.nab'] = true;
        $emailAddresses['test.user@test.nadex'] = true;
        $emailAddresses['test.user@test.nagoya'] = true;
        $emailAddresses['test.user@test.name'] = true;
        $emailAddresses['test.user@test.nationwide'] = true;
        $emailAddresses['test.user@test.natura'] = true;
        $emailAddresses['test.user@test.navy'] = true;
        $emailAddresses['test.user@test.nba'] = true;
        $emailAddresses['test.user@test.nc'] = true;
        $emailAddresses['test.user@test.ne'] = true;
        $emailAddresses['test.user@test.nec'] = true;
        $emailAddresses['test.user@test.net'] = true;
        $emailAddresses['test.user@test.netbank'] = true;
        $emailAddresses['test.user@test.netflix'] = true;
        $emailAddresses['test.user@test.network'] = true;
        $emailAddresses['test.user@test.neustar'] = true;
        $emailAddresses['test.user@test.new'] = true;
        $emailAddresses['test.user@test.newholland'] = true;
        $emailAddresses['test.user@test.news'] = true;
        $emailAddresses['test.user@test.next'] = true;
        $emailAddresses['test.user@test.nextdirect'] = true;
        $emailAddresses['test.user@test.nexus'] = true;
        $emailAddresses['test.user@test.nf'] = true;
        $emailAddresses['test.user@test.nfl'] = true;
        $emailAddresses['test.user@test.ng'] = true;
        $emailAddresses['test.user@test.ngo'] = true;
        $emailAddresses['test.user@test.nhk'] = true;
        $emailAddresses['test.user@test.ni'] = true;
        $emailAddresses['test.user@test.nico'] = true;
        $emailAddresses['test.user@test.nike'] = true;
        $emailAddresses['test.user@test.nikon'] = true;
        $emailAddresses['test.user@test.ninja'] = true;
        $emailAddresses['test.user@test.nissan'] = true;
        $emailAddresses['test.user@test.nissay'] = true;
        $emailAddresses['test.user@test.nl'] = true;
        $emailAddresses['test.user@test.no'] = true;
        $emailAddresses['test.user@test.nokia'] = true;
        $emailAddresses['test.user@test.northwesternmutual'] = true;
        $emailAddresses['test.user@test.norton'] = true;
        $emailAddresses['test.user@test.now'] = true;
        $emailAddresses['test.user@test.nowruz'] = true;
        $emailAddresses['test.user@test.nowtv'] = true;
        $emailAddresses['test.user@test.np'] = true;
        $emailAddresses['test.user@test.nr'] = true;
        $emailAddresses['test.user@test.nra'] = true;
        $emailAddresses['test.user@test.nrw'] = true;
        $emailAddresses['test.user@test.ntt'] = true;
        $emailAddresses['test.user@test.nu'] = true;
        $emailAddresses['test.user@test.nyc'] = true;
        $emailAddresses['test.user@test.nz'] = true;
        $emailAddresses['test.user@test.obi'] = true;
        $emailAddresses['test.user@test.observer'] = true;
        $emailAddresses['test.user@test.off'] = true;
        $emailAddresses['test.user@test.office'] = true;
        $emailAddresses['test.user@test.okinawa'] = true;
        $emailAddresses['test.user@test.olayan'] = true;
        $emailAddresses['test.user@test.olayangroup'] = true;
        $emailAddresses['test.user@test.oldnavy'] = true;
        $emailAddresses['test.user@test.ollo'] = true;
        $emailAddresses['test.user@test.om'] = true;
        $emailAddresses['test.user@test.omega'] = true;
        $emailAddresses['test.user@test.one'] = true;
        $emailAddresses['test.user@test.ong'] = true;
        $emailAddresses['test.user@test.onl'] = true;
        $emailAddresses['test.user@test.online'] = true;
        $emailAddresses['test.user@test.onyourside'] = true;
        $emailAddresses['test.user@test.ooo'] = true;
        $emailAddresses['test.user@test.open'] = true;
        $emailAddresses['test.user@test.oracle'] = true;
        $emailAddresses['test.user@test.orange'] = true;
        $emailAddresses['test.user@test.org'] = true;
        $emailAddresses['test.user@test.organic'] = true;
        $emailAddresses['test.user@test.origins'] = true;
        $emailAddresses['test.user@test.osaka'] = true;
        $emailAddresses['test.user@test.otsuka'] = true;
        $emailAddresses['test.user@test.ott'] = true;
        $emailAddresses['test.user@test.ovh'] = true;
        $emailAddresses['test.user@test.pa'] = true;
        $emailAddresses['test.user@test.page'] = true;
        $emailAddresses['test.user@test.panasonic'] = true;
        $emailAddresses['test.user@test.panerai'] = true;
        $emailAddresses['test.user@test.paris'] = true;
        $emailAddresses['test.user@test.pars'] = true;
        $emailAddresses['test.user@test.partners'] = true;
        $emailAddresses['test.user@test.parts'] = true;
        $emailAddresses['test.user@test.party'] = true;
        $emailAddresses['test.user@test.passagens'] = true;
        $emailAddresses['test.user@test.pay'] = true;
        $emailAddresses['test.user@test.pccw'] = true;
        $emailAddresses['test.user@test.pe'] = true;
        $emailAddresses['test.user@test.pet'] = true;
        $emailAddresses['test.user@test.pf'] = true;
        $emailAddresses['test.user@test.pfizer'] = true;
        $emailAddresses['test.user@test.pg'] = true;
        $emailAddresses['test.user@test.ph'] = true;
        $emailAddresses['test.user@test.pharmacy'] = true;
        $emailAddresses['test.user@test.phd'] = true;
        $emailAddresses['test.user@test.philips'] = true;
        $emailAddresses['test.user@test.phone'] = true;
        $emailAddresses['test.user@test.photo'] = true;
        $emailAddresses['test.user@test.photography'] = true;
        $emailAddresses['test.user@test.photos'] = true;
        $emailAddresses['test.user@test.physio'] = true;
        $emailAddresses['test.user@test.piaget'] = true;
        $emailAddresses['test.user@test.pics'] = true;
        $emailAddresses['test.user@test.pictet'] = true;
        $emailAddresses['test.user@test.pictures'] = true;
        $emailAddresses['test.user@test.pid'] = true;
        $emailAddresses['test.user@test.pin'] = true;
        $emailAddresses['test.user@test.ping'] = true;
        $emailAddresses['test.user@test.pink'] = true;
        $emailAddresses['test.user@test.pioneer'] = true;
        $emailAddresses['test.user@test.pizza'] = true;
        $emailAddresses['test.user@test.pk'] = true;
        $emailAddresses['test.user@test.pl'] = true;
        $emailAddresses['test.user@test.place'] = true;
        $emailAddresses['test.user@test.play'] = true;
        $emailAddresses['test.user@test.playstation'] = true;
        $emailAddresses['test.user@test.plumbing'] = true;
        $emailAddresses['test.user@test.plus'] = true;
        $emailAddresses['test.user@test.pm'] = true;
        $emailAddresses['test.user@test.pn'] = true;
        $emailAddresses['test.user@test.pnc'] = true;
        $emailAddresses['test.user@test.pohl'] = true;
        $emailAddresses['test.user@test.poker'] = true;
        $emailAddresses['test.user@test.politie'] = true;
        $emailAddresses['test.user@test.porn'] = true;
        $emailAddresses['test.user@test.post'] = true;
        $emailAddresses['test.user@test.pr'] = true;
        $emailAddresses['test.user@test.pramerica'] = true;
        $emailAddresses['test.user@test.praxi'] = true;
        $emailAddresses['test.user@test.press'] = true;
        $emailAddresses['test.user@test.prime'] = true;
        $emailAddresses['test.user@test.pro'] = true;
        $emailAddresses['test.user@test.prod'] = true;
        $emailAddresses['test.user@test.productions'] = true;
        $emailAddresses['test.user@test.prof'] = true;
        $emailAddresses['test.user@test.progressive'] = true;
        $emailAddresses['test.user@test.promo'] = true;
        $emailAddresses['test.user@test.properties'] = true;
        $emailAddresses['test.user@test.property'] = true;
        $emailAddresses['test.user@test.protection'] = true;
        $emailAddresses['test.user@test.pru'] = true;
        $emailAddresses['test.user@test.prudential'] = true;
        $emailAddresses['test.user@test.ps'] = true;
        $emailAddresses['test.user@test.pt'] = true;
        $emailAddresses['test.user@test.pub'] = true;
        $emailAddresses['test.user@test.pw'] = true;
        $emailAddresses['test.user@test.pwc'] = true;
        $emailAddresses['test.user@test.py'] = true;
        $emailAddresses['test.user@test.qa'] = true;
        $emailAddresses['test.user@test.qpon'] = true;
        $emailAddresses['test.user@test.quebec'] = true;
        $emailAddresses['test.user@test.quest'] = true;
        $emailAddresses['test.user@test.qvc'] = true;
        $emailAddresses['test.user@test.racing'] = true;
        $emailAddresses['test.user@test.radio'] = true;
        $emailAddresses['test.user@test.raid'] = true;
        $emailAddresses['test.user@test.re'] = true;
        $emailAddresses['test.user@test.read'] = true;
        $emailAddresses['test.user@test.realestate'] = true;
        $emailAddresses['test.user@test.realtor'] = true;
        $emailAddresses['test.user@test.realty'] = true;
        $emailAddresses['test.user@test.recipes'] = true;
        $emailAddresses['test.user@test.red'] = true;
        $emailAddresses['test.user@test.redstone'] = true;
        $emailAddresses['test.user@test.redumbrella'] = true;
        $emailAddresses['test.user@test.rehab'] = true;
        $emailAddresses['test.user@test.reise'] = true;
        $emailAddresses['test.user@test.reisen'] = true;
        $emailAddresses['test.user@test.reit'] = true;
        $emailAddresses['test.user@test.reliance'] = true;
        $emailAddresses['test.user@test.ren'] = true;
        $emailAddresses['test.user@test.rent'] = true;
        $emailAddresses['test.user@test.rentals'] = true;
        $emailAddresses['test.user@test.repair'] = true;
        $emailAddresses['test.user@test.report'] = true;
        $emailAddresses['test.user@test.republican'] = true;
        $emailAddresses['test.user@test.rest'] = true;
        $emailAddresses['test.user@test.restaurant'] = true;
        $emailAddresses['test.user@test.review'] = true;
        $emailAddresses['test.user@test.reviews'] = true;
        $emailAddresses['test.user@test.rexroth'] = true;
        $emailAddresses['test.user@test.rich'] = true;
        $emailAddresses['test.user@test.richardli'] = true;
        $emailAddresses['test.user@test.ricoh'] = true;
        $emailAddresses['test.user@test.rightathome'] = true;
        $emailAddresses['test.user@test.ril'] = true;
        $emailAddresses['test.user@test.rio'] = true;
        $emailAddresses['test.user@test.rip'] = true;
        $emailAddresses['test.user@test.rmit'] = true;
        $emailAddresses['test.user@test.ro'] = true;
        $emailAddresses['test.user@test.rocher'] = true;
        $emailAddresses['test.user@test.rocks'] = true;
        $emailAddresses['test.user@test.rodeo'] = true;
        $emailAddresses['test.user@test.rogers'] = true;
        $emailAddresses['test.user@test.room'] = true;
        $emailAddresses['test.user@test.rs'] = true;
        $emailAddresses['test.user@test.rsvp'] = true;
        $emailAddresses['test.user@test.ru'] = true;
        $emailAddresses['test.user@test.rugby'] = true;
        $emailAddresses['test.user@test.ruhr'] = true;
        $emailAddresses['test.user@test.run'] = true;
        $emailAddresses['test.user@test.rw'] = true;
        $emailAddresses['test.user@test.rwe'] = true;
        $emailAddresses['test.user@test.ryukyu'] = true;
        $emailAddresses['test.user@test.sa'] = true;
        $emailAddresses['test.user@test.saarland'] = true;
        $emailAddresses['test.user@test.safe'] = true;
        $emailAddresses['test.user@test.safety'] = true;
        $emailAddresses['test.user@test.sakura'] = true;
        $emailAddresses['test.user@test.sale'] = true;
        $emailAddresses['test.user@test.salon'] = true;
        $emailAddresses['test.user@test.samsclub'] = true;
        $emailAddresses['test.user@test.samsung'] = true;
        $emailAddresses['test.user@test.sandvik'] = true;
        $emailAddresses['test.user@test.sandvikcoromant'] = true;
        $emailAddresses['test.user@test.sanofi'] = true;
        $emailAddresses['test.user@test.sap'] = true;
        $emailAddresses['test.user@test.sapo'] = true;
        $emailAddresses['test.user@test.sarl'] = true;
        $emailAddresses['test.user@test.sas'] = true;
        $emailAddresses['test.user@test.save'] = true;
        $emailAddresses['test.user@test.saxo'] = true;
        $emailAddresses['test.user@test.sb'] = true;
        $emailAddresses['test.user@test.sbi'] = true;
        $emailAddresses['test.user@test.sbs'] = true;
        $emailAddresses['test.user@test.sc'] = true;
        $emailAddresses['test.user@test.sca'] = true;
        $emailAddresses['test.user@test.scb'] = true;
        $emailAddresses['test.user@test.schaeffler'] = true;
        $emailAddresses['test.user@test.schmidt'] = true;
        $emailAddresses['test.user@test.scholarships'] = true;
        $emailAddresses['test.user@test.school'] = true;
        $emailAddresses['test.user@test.schule'] = true;
        $emailAddresses['test.user@test.schwarz'] = true;
        $emailAddresses['test.user@test.science'] = true;
        $emailAddresses['test.user@test.scjohnson'] = true;
        $emailAddresses['test.user@test.scor'] = true;
        $emailAddresses['test.user@test.scot'] = true;
        $emailAddresses['test.user@test.sd'] = true;
        $emailAddresses['test.user@test.se'] = true;
        $emailAddresses['test.user@test.search'] = true;
        $emailAddresses['test.user@test.seat'] = true;
        $emailAddresses['test.user@test.secure'] = true;
        $emailAddresses['test.user@test.security'] = true;
        $emailAddresses['test.user@test.seek'] = true;
        $emailAddresses['test.user@test.select'] = true;
        $emailAddresses['test.user@test.sener'] = true;
        $emailAddresses['test.user@test.services'] = true;
        $emailAddresses['test.user@test.ses'] = true;
        $emailAddresses['test.user@test.seven'] = true;
        $emailAddresses['test.user@test.sew'] = true;
        $emailAddresses['test.user@test.sex'] = true;
        $emailAddresses['test.user@test.sexy'] = true;
        $emailAddresses['test.user@test.sfr'] = true;
        $emailAddresses['test.user@test.sg'] = true;
        $emailAddresses['test.user@test.sh'] = true;
        $emailAddresses['test.user@test.shangrila'] = true;
        $emailAddresses['test.user@test.sharp'] = true;
        $emailAddresses['test.user@test.shaw'] = true;
        $emailAddresses['test.user@test.shell'] = true;
        $emailAddresses['test.user@test.shia'] = true;
        $emailAddresses['test.user@test.shiksha'] = true;
        $emailAddresses['test.user@test.shoes'] = true;
        $emailAddresses['test.user@test.shop'] = true;
        $emailAddresses['test.user@test.shopping'] = true;
        $emailAddresses['test.user@test.shouji'] = true;
        $emailAddresses['test.user@test.show'] = true;
        $emailAddresses['test.user@test.showtime'] = true;
        $emailAddresses['test.user@test.shriram'] = true;
        $emailAddresses['test.user@test.si'] = true;
        $emailAddresses['test.user@test.silk'] = true;
        $emailAddresses['test.user@test.sina'] = true;
        $emailAddresses['test.user@test.singles'] = true;
        $emailAddresses['test.user@test.site'] = true;
        $emailAddresses['test.user@test.sj'] = true;
        $emailAddresses['test.user@test.sk'] = true;
        $emailAddresses['test.user@test.ski'] = true;
        $emailAddresses['test.user@test.skin'] = true;
        $emailAddresses['test.user@test.sky'] = true;
        $emailAddresses['test.user@test.skype'] = true;
        $emailAddresses['test.user@test.sl'] = true;
        $emailAddresses['test.user@test.sling'] = true;
        $emailAddresses['test.user@test.sm'] = true;
        $emailAddresses['test.user@test.smart'] = true;
        $emailAddresses['test.user@test.smile'] = true;
        $emailAddresses['test.user@test.sn'] = true;
        $emailAddresses['test.user@test.sncf'] = true;
        $emailAddresses['test.user@test.so'] = true;
        $emailAddresses['test.user@test.soccer'] = true;
        $emailAddresses['test.user@test.social'] = true;
        $emailAddresses['test.user@test.softbank'] = true;
        $emailAddresses['test.user@test.software'] = true;
        $emailAddresses['test.user@test.sohu'] = true;
        $emailAddresses['test.user@test.solar'] = true;
        $emailAddresses['test.user@test.solutions'] = true;
        $emailAddresses['test.user@test.song'] = true;
        $emailAddresses['test.user@test.sony'] = true;
        $emailAddresses['test.user@test.soy'] = true;
        $emailAddresses['test.user@test.space'] = true;
        $emailAddresses['test.user@test.spiegel'] = true;
        $emailAddresses['test.user@test.sport'] = true;
        $emailAddresses['test.user@test.spot'] = true;
        $emailAddresses['test.user@test.spreadbetting'] = true;
        $emailAddresses['test.user@test.sr'] = true;
        $emailAddresses['test.user@test.srl'] = true;
        $emailAddresses['test.user@test.srt'] = true;
        $emailAddresses['test.user@test.st'] = true;
        $emailAddresses['test.user@test.stada'] = true;
        $emailAddresses['test.user@test.staples'] = true;
        $emailAddresses['test.user@test.star'] = true;
        $emailAddresses['test.user@test.starhub'] = true;
        $emailAddresses['test.user@test.statebank'] = true;
        $emailAddresses['test.user@test.statefarm'] = true;
        $emailAddresses['test.user@test.statoil'] = true;
        $emailAddresses['test.user@test.stc'] = true;
        $emailAddresses['test.user@test.stcgroup'] = true;
        $emailAddresses['test.user@test.stockholm'] = true;
        $emailAddresses['test.user@test.storage'] = true;
        $emailAddresses['test.user@test.store'] = true;
        $emailAddresses['test.user@test.stream'] = true;
        $emailAddresses['test.user@test.studio'] = true;
        $emailAddresses['test.user@test.study'] = true;
        $emailAddresses['test.user@test.style'] = true;
        $emailAddresses['test.user@test.su'] = true;
        $emailAddresses['test.user@test.sucks'] = true;
        $emailAddresses['test.user@test.supplies'] = true;
        $emailAddresses['test.user@test.supply'] = true;
        $emailAddresses['test.user@test.support'] = true;
        $emailAddresses['test.user@test.surf'] = true;
        $emailAddresses['test.user@test.surgery'] = true;
        $emailAddresses['test.user@test.suzuki'] = true;
        $emailAddresses['test.user@test.sv'] = true;
        $emailAddresses['test.user@test.swatch'] = true;
        $emailAddresses['test.user@test.swiftcover'] = true;
        $emailAddresses['test.user@test.swiss'] = true;
        $emailAddresses['test.user@test.sx'] = true;
        $emailAddresses['test.user@test.sy'] = true;
        $emailAddresses['test.user@test.sydney'] = true;
        $emailAddresses['test.user@test.symantec'] = true;
        $emailAddresses['test.user@test.systems'] = true;
        $emailAddresses['test.user@test.sz'] = true;
        $emailAddresses['test.user@test.tab'] = true;
        $emailAddresses['test.user@test.taipei'] = true;
        $emailAddresses['test.user@test.talk'] = true;
        $emailAddresses['test.user@test.taobao'] = true;
        $emailAddresses['test.user@test.target'] = true;
        $emailAddresses['test.user@test.tatamotors'] = true;
        $emailAddresses['test.user@test.tatar'] = true;
        $emailAddresses['test.user@test.tattoo'] = true;
        $emailAddresses['test.user@test.tax'] = true;
        $emailAddresses['test.user@test.taxi'] = true;
        $emailAddresses['test.user@test.tc'] = true;
        $emailAddresses['test.user@test.tci'] = true;
        $emailAddresses['test.user@test.td'] = true;
        $emailAddresses['test.user@test.tdk'] = true;
        $emailAddresses['test.user@test.team'] = true;
        $emailAddresses['test.user@test.tech'] = true;
        $emailAddresses['test.user@test.technology'] = true;
        $emailAddresses['test.user@test.tel'] = true;
        $emailAddresses['test.user@test.telecity'] = true;
        $emailAddresses['test.user@test.telefonica'] = true;
        $emailAddresses['test.user@test.temasek'] = true;
        $emailAddresses['test.user@test.tennis'] = true;
        $emailAddresses['test.user@test.teva'] = true;
        $emailAddresses['test.user@test.tf'] = true;
        $emailAddresses['test.user@test.tg'] = true;
        $emailAddresses['test.user@test.th'] = true;
        $emailAddresses['test.user@test.thd'] = true;
        $emailAddresses['test.user@test.theater'] = true;
        $emailAddresses['test.user@test.theatre'] = true;
        $emailAddresses['test.user@test.tiaa'] = true;
        $emailAddresses['test.user@test.tickets'] = true;
        $emailAddresses['test.user@test.tienda'] = true;
        $emailAddresses['test.user@test.tiffany'] = true;
        $emailAddresses['test.user@test.tips'] = true;
        $emailAddresses['test.user@test.tires'] = true;
        $emailAddresses['test.user@test.tirol'] = true;
        $emailAddresses['test.user@test.tj'] = true;
        $emailAddresses['test.user@test.tjmaxx'] = true;
        $emailAddresses['test.user@test.tjx'] = true;
        $emailAddresses['test.user@test.tk'] = true;
        $emailAddresses['test.user@test.tkmaxx'] = true;
        $emailAddresses['test.user@test.tl'] = true;
        $emailAddresses['test.user@test.tm'] = true;
        $emailAddresses['test.user@test.tmall'] = true;
        $emailAddresses['test.user@test.tn'] = true;
        $emailAddresses['test.user@test.to'] = true;
        $emailAddresses['test.user@test.today'] = true;
        $emailAddresses['test.user@test.tokyo'] = true;
        $emailAddresses['test.user@test.tools'] = true;
        $emailAddresses['test.user@test.top'] = true;
        $emailAddresses['test.user@test.toray'] = true;
        $emailAddresses['test.user@test.toshiba'] = true;
        $emailAddresses['test.user@test.total'] = true;
        $emailAddresses['test.user@test.tours'] = true;
        $emailAddresses['test.user@test.town'] = true;
        $emailAddresses['test.user@test.toyota'] = true;
        $emailAddresses['test.user@test.toys'] = true;
        $emailAddresses['test.user@test.tr'] = true;
        $emailAddresses['test.user@test.trade'] = true;
        $emailAddresses['test.user@test.trading'] = true;
        $emailAddresses['test.user@test.training'] = true;
        $emailAddresses['test.user@test.travel'] = true;
        $emailAddresses['test.user@test.travelchannel'] = true;
        $emailAddresses['test.user@test.travelers'] = true;
        $emailAddresses['test.user@test.travelersinsurance'] = true;
        $emailAddresses['test.user@test.trust'] = true;
        $emailAddresses['test.user@test.trv'] = true;
        $emailAddresses['test.user@test.tt'] = true;
        $emailAddresses['test.user@test.tube'] = true;
        $emailAddresses['test.user@test.tui'] = true;
        $emailAddresses['test.user@test.tunes'] = true;
        $emailAddresses['test.user@test.tushu'] = true;
        $emailAddresses['test.user@test.tv'] = true;
        $emailAddresses['test.user@test.tvs'] = true;
        $emailAddresses['test.user@test.tw'] = true;
        $emailAddresses['test.user@test.tz'] = true;
        $emailAddresses['test.user@test.ua'] = true;
        $emailAddresses['test.user@test.ubank'] = true;
        $emailAddresses['test.user@test.ubs'] = true;
        $emailAddresses['test.user@test.uconnect'] = true;
        $emailAddresses['test.user@test.ug'] = true;
        $emailAddresses['test.user@test.uk'] = true;
        $emailAddresses['test.user@test.unicom'] = true;
        $emailAddresses['test.user@test.university'] = true;
        $emailAddresses['test.user@test.uno'] = true;
        $emailAddresses['test.user@test.uol'] = true;
        $emailAddresses['test.user@test.ups'] = true;
        $emailAddresses['test.user@test.us'] = true;
        $emailAddresses['test.user@test.uy'] = true;
        $emailAddresses['test.user@test.uz'] = true;
        $emailAddresses['test.user@test.va'] = true;
        $emailAddresses['test.user@test.vacations'] = true;
        $emailAddresses['test.user@test.vana'] = true;
        $emailAddresses['test.user@test.vanguard'] = true;
        $emailAddresses['test.user@test.vc'] = true;
        $emailAddresses['test.user@test.ve'] = true;
        $emailAddresses['test.user@test.vegas'] = true;
        $emailAddresses['test.user@test.ventures'] = true;
        $emailAddresses['test.user@test.verisign'] = true;
        $emailAddresses['test.user@test.versicherung'] = true;
        $emailAddresses['test.user@test.vet'] = true;
        $emailAddresses['test.user@test.vg'] = true;
        $emailAddresses['test.user@test.vi'] = true;
        $emailAddresses['test.user@test.viajes'] = true;
        $emailAddresses['test.user@test.video'] = true;
        $emailAddresses['test.user@test.vig'] = true;
        $emailAddresses['test.user@test.viking'] = true;
        $emailAddresses['test.user@test.villas'] = true;
        $emailAddresses['test.user@test.vin'] = true;
        $emailAddresses['test.user@test.vip'] = true;
        $emailAddresses['test.user@test.virgin'] = true;
        $emailAddresses['test.user@test.visa'] = true;
        $emailAddresses['test.user@test.vision'] = true;
        $emailAddresses['test.user@test.vista'] = true;
        $emailAddresses['test.user@test.vistaprint'] = true;
        $emailAddresses['test.user@test.viva'] = true;
        $emailAddresses['test.user@test.vivo'] = true;
        $emailAddresses['test.user@test.vlaanderen'] = true;
        $emailAddresses['test.user@test.vn'] = true;
        $emailAddresses['test.user@test.vodka'] = true;
        $emailAddresses['test.user@test.volkswagen'] = true;
        $emailAddresses['test.user@test.volvo'] = true;
        $emailAddresses['test.user@test.vote'] = true;
        $emailAddresses['test.user@test.voting'] = true;
        $emailAddresses['test.user@test.voto'] = true;
        $emailAddresses['test.user@test.voyage'] = true;
        $emailAddresses['test.user@test.vu'] = true;
        $emailAddresses['test.user@test.vuelos'] = true;
        $emailAddresses['test.user@test.wales'] = true;
        $emailAddresses['test.user@test.walmart'] = true;
        $emailAddresses['test.user@test.walter'] = true;
        $emailAddresses['test.user@test.wang'] = true;
        $emailAddresses['test.user@test.wanggou'] = true;
        $emailAddresses['test.user@test.warman'] = true;
        $emailAddresses['test.user@test.watch'] = true;
        $emailAddresses['test.user@test.watches'] = true;
        $emailAddresses['test.user@test.weather'] = true;
        $emailAddresses['test.user@test.weatherchannel'] = true;
        $emailAddresses['test.user@test.webcam'] = true;
        $emailAddresses['test.user@test.weber'] = true;
        $emailAddresses['test.user@test.website'] = true;
        $emailAddresses['test.user@test.wed'] = true;
        $emailAddresses['test.user@test.wedding'] = true;
        $emailAddresses['test.user@test.weibo'] = true;
        $emailAddresses['test.user@test.weir'] = true;
        $emailAddresses['test.user@test.wf'] = true;
        $emailAddresses['test.user@test.whoswho'] = true;
        $emailAddresses['test.user@test.wien'] = true;
        $emailAddresses['test.user@test.wiki'] = true;
        $emailAddresses['test.user@test.williamhill'] = true;
        $emailAddresses['test.user@test.win'] = true;
        $emailAddresses['test.user@test.windows'] = true;
        $emailAddresses['test.user@test.wine'] = true;
        $emailAddresses['test.user@test.winners'] = true;
        $emailAddresses['test.user@test.wme'] = true;
        $emailAddresses['test.user@test.wolterskluwer'] = true;
        $emailAddresses['test.user@test.woodside'] = true;
        $emailAddresses['test.user@test.work'] = true;
        $emailAddresses['test.user@test.works'] = true;
        $emailAddresses['test.user@test.world'] = true;
        $emailAddresses['test.user@test.wow'] = true;
        $emailAddresses['test.user@test.ws'] = true;
        $emailAddresses['test.user@test.wtc'] = true;
        $emailAddresses['test.user@test.wtf'] = true;
        $emailAddresses['test.user@test.xbox'] = true;
        $emailAddresses['test.user@test.xerox'] = true;
        $emailAddresses['test.user@test.xfinity'] = true;
        $emailAddresses['test.user@test.xihuan'] = true;
        $emailAddresses['test.user@test.xin'] = true;
        $emailAddresses['test.user@test.xn--11b4c3d'] = true;
        $emailAddresses['test.user@test.xn--1ck2e1b'] = true;
        $emailAddresses['test.user@test.xn--1qqw23a'] = true;
        $emailAddresses['test.user@test.xn--2scrj9c'] = true;
        $emailAddresses['test.user@test.xn--30rr7y'] = true;
        $emailAddresses['test.user@test.xn--3bst00m'] = true;
        $emailAddresses['test.user@test.xn--3ds443g'] = true;
        $emailAddresses['test.user@test.xn--3e0b707e'] = true;
        $emailAddresses['test.user@test.xn--3hcrj9c'] = true;
        $emailAddresses['test.user@test.xn--3oq18vl8pn36a'] = true;
        $emailAddresses['test.user@test.xn--3pxu8k'] = true;
        $emailAddresses['test.user@test.xn--42c2d9a'] = true;
        $emailAddresses['test.user@test.xn--45br5cyl'] = true;
        $emailAddresses['test.user@test.xn--45brj9c'] = true;
        $emailAddresses['test.user@test.xn--45q11c'] = true;
        $emailAddresses['test.user@test.xn--4gbrim'] = true;
        $emailAddresses['test.user@test.xn--54b7fta0cc'] = true;
        $emailAddresses['test.user@test.xn--55qw42g'] = true;
        $emailAddresses['test.user@test.xn--55qx5d'] = true;
        $emailAddresses['test.user@test.xn--5su34j936bgsg'] = true;
        $emailAddresses['test.user@test.xn--5tzm5g'] = true;
        $emailAddresses['test.user@test.xn--6frz82g'] = true;
        $emailAddresses['test.user@test.xn--6qq986b3xl'] = true;
        $emailAddresses['test.user@test.xn--80adxhks'] = true;
        $emailAddresses['test.user@test.xn--80ao21a'] = true;
        $emailAddresses['test.user@test.xn--80aqecdr1a'] = true;
        $emailAddresses['test.user@test.xn--80asehdb'] = true;
        $emailAddresses['test.user@test.xn--80aswg'] = true;
        $emailAddresses['test.user@test.xn--8y0a063a'] = true;
        $emailAddresses['test.user@test.xn--90a3ac'] = true;
        $emailAddresses['test.user@test.xn--90ae'] = true;
        $emailAddresses['test.user@test.xn--90ais'] = true;
        $emailAddresses['test.user@test.xn--9dbq2a'] = true;
        $emailAddresses['test.user@test.xn--9et52u'] = true;
        $emailAddresses['test.user@test.xn--9krt00a'] = true;
        $emailAddresses['test.user@test.xn--b4w605ferd'] = true;
        $emailAddresses['test.user@test.xn--bck1b9a5dre4c'] = true;
        $emailAddresses['test.user@test.xn--c1avg'] = true;
        $emailAddresses['test.user@test.xn--c2br7g'] = true;
        $emailAddresses['test.user@test.xn--cck2b3b'] = true;
        $emailAddresses['test.user@test.xn--cg4bki'] = true;
        $emailAddresses['test.user@test.xn--clchc0ea0b2g2a9gcd'] = true;
        $emailAddresses['test.user@test.xn--czr694b'] = true;
        $emailAddresses['test.user@test.xn--czrs0t'] = true;
        $emailAddresses['test.user@test.xn--czru2d'] = true;
        $emailAddresses['test.user@test.xn--d1acj3b'] = true;
        $emailAddresses['test.user@test.xn--d1alf'] = true;
        $emailAddresses['test.user@test.xn--e1a4c'] = true;
        $emailAddresses['test.user@test.xn--eckvdtc9d'] = true;
        $emailAddresses['test.user@test.xn--efvy88h'] = true;
        $emailAddresses['test.user@test.xn--estv75g'] = true;
        $emailAddresses['test.user@test.xn--fct429k'] = true;
        $emailAddresses['test.user@test.xn--fhbei'] = true;
        $emailAddresses['test.user@test.xn--fiq228c5hs'] = true;
        $emailAddresses['test.user@test.xn--fiq64b'] = true;
        $emailAddresses['test.user@test.xn--fiqs8s'] = true;
        $emailAddresses['test.user@test.xn--fiqz9s'] = true;
        $emailAddresses['test.user@test.xn--fjq720a'] = true;
        $emailAddresses['test.user@test.xn--flw351e'] = true;
        $emailAddresses['test.user@test.xn--fpcrj9c3d'] = true;
        $emailAddresses['test.user@test.xn--fzc2c9e2c'] = true;
        $emailAddresses['test.user@test.xn--fzys8d69uvgm'] = true;
        $emailAddresses['test.user@test.xn--g2xx48c'] = true;
        $emailAddresses['test.user@test.xn--gckr3f0f'] = true;
        $emailAddresses['test.user@test.xn--gecrj9c'] = true;
        $emailAddresses['test.user@test.xn--gk3at1e'] = true;
        $emailAddresses['test.user@test.xn--h2breg3eve'] = true;
        $emailAddresses['test.user@test.xn--h2brj9c'] = true;
        $emailAddresses['test.user@test.xn--h2brj9c8c'] = true;
        $emailAddresses['test.user@test.xn--hxt814e'] = true;
        $emailAddresses['test.user@test.xn--i1b6b1a6a2e'] = true;
        $emailAddresses['test.user@test.xn--imr513n'] = true;
        $emailAddresses['test.user@test.xn--io0a7i'] = true;
        $emailAddresses['test.user@test.xn--j1aef'] = true;
        $emailAddresses['test.user@test.xn--j1amh'] = true;
        $emailAddresses['test.user@test.xn--j6w193g'] = true;
        $emailAddresses['test.user@test.xn--jlq61u9w7b'] = true;
        $emailAddresses['test.user@test.xn--jvr189m'] = true;
        $emailAddresses['test.user@test.xn--kcrx77d1x4a'] = true;
        $emailAddresses['test.user@test.xn--kprw13d'] = true;
        $emailAddresses['test.user@test.xn--kpry57d'] = true;
        $emailAddresses['test.user@test.xn--kpu716f'] = true;
        $emailAddresses['test.user@test.xn--kput3i'] = true;
        $emailAddresses['test.user@test.xn--l1acc'] = true;
        $emailAddresses['test.user@test.xn--lgbbat1ad8j'] = true;
        $emailAddresses['test.user@test.xn--mgb9awbf'] = true;
        $emailAddresses['test.user@test.xn--mgba3a3ejt'] = true;
        $emailAddresses['test.user@test.xn--mgba3a4f16a'] = true;
        $emailAddresses['test.user@test.xn--mgba7c0bbn0a'] = true;
        $emailAddresses['test.user@test.xn--mgbaakc7dvf'] = true;
        $emailAddresses['test.user@test.xn--mgbaam7a8h'] = true;
        $emailAddresses['test.user@test.xn--mgbab2bd'] = true;
        $emailAddresses['test.user@test.xn--mgbai9azgqp6j'] = true;
        $emailAddresses['test.user@test.xn--mgbayh7gpa'] = true;
        $emailAddresses['test.user@test.xn--mgbb9fbpob'] = true;
        $emailAddresses['test.user@test.xn--mgbbh1a'] = true;
        $emailAddresses['test.user@test.xn--mgbbh1a71e'] = true;
        $emailAddresses['test.user@test.xn--mgbc0a9azcg'] = true;
        $emailAddresses['test.user@test.xn--mgbca7dzdo'] = true;
        $emailAddresses['test.user@test.xn--mgberp4a5d4ar'] = true;
        $emailAddresses['test.user@test.xn--mgbgu82a'] = true;
        $emailAddresses['test.user@test.xn--mgbi4ecexp'] = true;
        $emailAddresses['test.user@test.xn--mgbpl2fh'] = true;
        $emailAddresses['test.user@test.xn--mgbt3dhd'] = true;
        $emailAddresses['test.user@test.xn--mgbtx2b'] = true;
        $emailAddresses['test.user@test.xn--mgbx4cd0ab'] = true;
        $emailAddresses['test.user@test.xn--mix891f'] = true;
        $emailAddresses['test.user@test.xn--mk1bu44c'] = true;
        $emailAddresses['test.user@test.xn--mxtq1m'] = true;
        $emailAddresses['test.user@test.xn--ngbc5azd'] = true;
        $emailAddresses['test.user@test.xn--ngbe9e0a'] = true;
        $emailAddresses['test.user@test.xn--ngbrx'] = true;
        $emailAddresses['test.user@test.xn--node'] = true;
        $emailAddresses['test.user@test.xn--nqv7f'] = true;
        $emailAddresses['test.user@test.xn--nqv7fs00ema'] = true;
        $emailAddresses['test.user@test.xn--nyqy26a'] = true;
        $emailAddresses['test.user@test.xn--o3cw4h'] = true;
        $emailAddresses['test.user@test.xn--ogbpf8fl'] = true;
        $emailAddresses['test.user@test.xn--otu796d'] = true;
        $emailAddresses['test.user@test.xn--p1acf'] = true;
        $emailAddresses['test.user@test.xn--p1ai'] = true;
        $emailAddresses['test.user@test.xn--pbt977c'] = true;
        $emailAddresses['test.user@test.xn--pgbs0dh'] = true;
        $emailAddresses['test.user@test.xn--pssy2u'] = true;
        $emailAddresses['test.user@test.xn--q9jyb4c'] = true;
        $emailAddresses['test.user@test.xn--qcka1pmc'] = true;
        $emailAddresses['test.user@test.xn--qxam'] = true;
        $emailAddresses['test.user@test.xn--rhqv96g'] = true;
        $emailAddresses['test.user@test.xn--rovu88b'] = true;
        $emailAddresses['test.user@test.xn--rvc1e0am3e'] = true;
        $emailAddresses['test.user@test.xn--s9brj9c'] = true;
        $emailAddresses['test.user@test.xn--ses554g'] = true;
        $emailAddresses['test.user@test.xn--t60b56a'] = true;
        $emailAddresses['test.user@test.xn--tckwe'] = true;
        $emailAddresses['test.user@test.xn--tiq49xqyj'] = true;
        $emailAddresses['test.user@test.xn--unup4y'] = true;
        $emailAddresses['test.user@test.xn--vermgensberater-ctb'] = true;
        $emailAddresses['test.user@test.xn--vermgensberatung-pwb'] = true;
        $emailAddresses['test.user@test.xn--vhquv'] = true;
        $emailAddresses['test.user@test.xn--vuq861b'] = true;
        $emailAddresses['test.user@test.xn--w4r85el8fhu5dnra'] = true;
        $emailAddresses['test.user@test.xn--w4rs40l'] = true;
        $emailAddresses['test.user@test.xn--wgbh1c'] = true;
        $emailAddresses['test.user@test.xn--wgbl6a'] = true;
        $emailAddresses['test.user@test.xn--xhq521b'] = true;
        $emailAddresses['test.user@test.xn--xkc2al3hye2a'] = true;
        $emailAddresses['test.user@test.xn--xkc2dl3a5ee0h'] = true;
        $emailAddresses['test.user@test.xn--y9a3aq'] = true;
        $emailAddresses['test.user@test.xn--yfro4i67o'] = true;
        $emailAddresses['test.user@test.xn--ygbi2ammx'] = true;
        $emailAddresses['test.user@test.xn--zfr164b'] = true;
        $emailAddresses['test.user@test.xperia'] = true;
        $emailAddresses['test.user@test.xxx'] = true;
        $emailAddresses['test.user@test.xyz'] = true;
        $emailAddresses['test.user@test.yachts'] = true;
        $emailAddresses['test.user@test.yahoo'] = true;
        $emailAddresses['test.user@test.yamaxun'] = true;
        $emailAddresses['test.user@test.yandex'] = true;
        $emailAddresses['test.user@test.ye'] = true;
        $emailAddresses['test.user@test.yodobashi'] = true;
        $emailAddresses['test.user@test.yoga'] = true;
        $emailAddresses['test.user@test.yokohama'] = true;
        $emailAddresses['test.user@test.you'] = true;
        $emailAddresses['test.user@test.youtube'] = true;
        $emailAddresses['test.user@test.yt'] = true;
        $emailAddresses['test.user@test.yun'] = true;
        $emailAddresses['test.user@test.za'] = true;
        $emailAddresses['test.user@test.zappos'] = true;
        $emailAddresses['test.user@test.zara'] = true;
        $emailAddresses['test.user@test.zero'] = true;
        $emailAddresses['test.user@test.zip'] = true;
        $emailAddresses['test.user@test.zippo'] = true;
        $emailAddresses['test.user@test.zm'] = true;
        $emailAddresses['test.user@test.zone'] = true;
        $emailAddresses['test.user@test.zuerich'] = true;
        $emailAddresses['test.user@test.zw'] = true;
        $emailAddresses['tester@intra.local'] = true;
        $emailAddresses['q@q.c;om'] = false;
        
        foreach( $emailAddresses as $emailAddress => $result) {
            if ($result == true) {
                $this->assertTrue(check_email($emailAddress));
            }
            else {
                $this->assertFalse(check_email($emailAddress));
            }
        }
        
    }

    public function test_generate_password() {

        $pw = generate_password();
        $len = strlen($pw);
        $this->assertEquals(8, $len);
        
    }

    public function test_generatePassword() {

        $pw = generatePassword('y');
        $len = strlen($pw);
        $this->assertEquals(14, $len);
        
        $pw = generatePassword('n');
        $len = strlen($pw);
        $this->assertEquals(8, $len);
        
    }
    
}

?>